INST_DIR := /usr/lib/apio/packages/tool-scons

all:

install:
	install -m 0755 -d $(DESTDIR)$(INST_DIR)/script/
	ln -s /usr/bin/scons $(DESTDIR)$(INST_DIR)/script/scons
	install -m 0644 package.json $(DESTDIR)$(INST_DIR)/



